config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'experiences#index'
  resources :users, only: :show
  resources :experiences do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :experience
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :experiences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @experience = Experience.find(params[:experience_id])
  end

  def create
    @experience = Experience.find(params[:experience_id])
    @booking = Booking.new(booking_params)
    @booking.experience = @experience
    @booking.user = current_user
    if @booking.save!
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :experience_id, :booking_date, :booking_details)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    @experiences = Experience.all
  end

  def new
    @experience = Experience.new
  end

  def show
    @experience = Experience.find(params[:id])
    @booking = Booking.new
  end

  def create
    @experience = Experience.new(experiences_params)
    @experience.user = current_user
    if @experience.save
      redirect_to experiences_path
    else
      render :new
    end
  end

  private

  def experiences_params
    params.require(:experience).permit(:title, :address, :description, :price, :rating, :user_id)
  end

  def find_experience
    @experience = Experience.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= simple_form_for ([@experience, @booking]) do |f| %>
  <%= f.input :booking_details, placeholder: 'what to do in here?' %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', experiences_path  %>


<!-- <form action="/lists/:list_id/bookmarks"></form> -->

app/views/experiences/index.html.erb
<!-- this is the banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1505761671935-60b3a7427bad?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">


    <h1>London Film Experiences</h1>
    <p style= "font-size: 24px,">We bring you an unique way of experience movies in <strong>London</strong>!</p>
    <p>Check out all the different movies that you can enjoy on the street of this cinematographic city.</p>
    <!-- <a class="btn btn-flat" href="#">Apply now</a> -->
  </div>
</div>
<!-- this is the end of banner -->



<!-- this is the iteration through the cards -->
  <div class= "card-space">
    <div class="cards">
    <% @experiences.each do |experience| %>
        <%= link_to experience_path(experience) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= experience.image_url %>)">
          </div>
        <% end %>
    <% end %>
    </div>
  </div>

<%#= link_to '- Add new experience -', new_experience_path  %>
<!-- this is the end of iteration through the cards -->

app/views/experiences/new.html.erb
<div class="box3">
    <div class='add-new-experience-form'>
      <%= simple_form_for(@experience) do |f| %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>

app/views/experiences/show.html.erb
<div class="container d-flex">
  <div class="experience-info">
    <div class="box2">
      <h1> <%= @experience.title %> </h1>
      <h3> <i> <%=  @experience.address %> </i> </h3>
      <p> <%= @experience.description %> </p>
      <a target='_blank' href="https://www.google.com/maps/place/Blackfriars+Bridge/@51.5096426,-0.1065715,17z/data=!3m1!4b1!4m5!3m4!1s0x487604ad954d31a7:0x4e26b9c44832a446!8m2!3d51.5096426!4d-0.1043828" class="btn btn-primary align-items"><i><i class="fas fa-map-marker-alt"></i></i>Take me there!</a>
      <div class="ratings-price d-flex">
        <p> <i class="fas fa-star" id="star"></i> <%= @experience.rating %> </p>
        <p> <strong>Price:</strong> £<%= @experience.price %>
      </div>
    </div>
    <%#= link_to ‘I want this experience’, new_experience_booking_path %>
    <%#= simple_form_for ([@experience, @booking]) do |f| %>
      <%#= f.input :date,  %>
    <%# end %>
    <%= simple_form_for([@experience, @booking]) do |f| %>
      <%= f.input :booking_date %>
      <%= f.input :booking_details, label: 'Any questions or requests?', placeholder: 'Please type your message here.' %>
      <%= f.submit %>
    <% end %>
    <%= link_to  'Back to Experiences', experiences_path, class: "btn btn-primary m-3" %>
  </div>
  <%= image_tag @experience.image_url , alt: "", class: "experience-img" %>
</div>



<!-- ORIGINAL -->
<!-- <div class="img__wrap">
  <img class="img__img" src="http://placehold.it/257x200.jpg" />
  <p class="img__description">sdfs<%= @experience.quote %></p>
</div>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOVIEExperiences</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%#= link_to "#", class: "navbar-brand" do %>
        <%#= image_tag "https://media.istockphoto.com/photos/empty-movie-clapper-board-picture-id614836096?k=6&m=614836096&s=612x612&w=0&h=yYr_e2iInGOUVcnkNv6NSe605CGWcf7AC0czd292RhE=" %>
        <%# end %>
      <a href="#" target="_blank"><i class="fas fa-film"></i></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if current_user %>
            <li class="nav-item dropdown">
                <span>Welcome, Tom!</span>
                <img src="https://images.mubicdn.net/images/cast_member/2184/cache-2992-1547409411/image-w856.jpg?size=800x" alt="#" class="img-tom">
                <i class="fas fa-list-ul" id="navbarDropdown" data-toggle="dropdown"></i>
                <%#= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "New Experience", new_experience_path, class: "dropdown-item" %>
                  <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          <% else  %>
              <li class="nav-item active btn btn-ghost" href="#">
              <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
              </li>
          <% end %>
                </div>
            </li>
        </ul>
      </div>
    </div>
    <div class="wrapper">
<!-- start of old navbar -->
<!--
    <p class="notice"><%#= notice %></p>
    <p class="alert"><%#= alert %></p>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%#= link_to "#", class: "navbar-brand" do %>
        <%#= image_tag "https://media.istockphoto.com/photos/empty-movie-clapper-board-picture-id614836096?k=6&m=614836096&s=612x612&w=0&h=yYr_e2iInGOUVcnkNv6NSe605CGWcf7AC0czd292RhE=" %>
        <%# end %>

      <a href="#" target="_blank"><i class="fas fa-film"></i></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <#% if current_user %>
            <li class="nav-item dropdown">
                <span>Welcome, Tom!</span>
                <%#= image_tag "https://images.mubicdn.net/images/cast_member/2184/cache-2992-1547409411/image-w856.jpg?size=800x", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                  <%#= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %>
                  <%#= link_to "New Experience", new_experience_path, class: "dropdown-item" %>
                  <%#= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          <%# else  %>
              <li class="nav-item active btn btn-ghost" href="#">
              <%#= link_to "Sign in", new_user_session_path, class: "nav-link" %>
              </li>
          <%# end %>
                </div>
            </li>
        </ul>
      </div>
    </div>



    <div class="navbar-container">
      <div class="row justify-content-center">
        <div class="col-10">
          <%#= "Discover where unforgettable scenes from your favorite movies were shot and be part of an experience to remember" %>
        </div>
      </div>
    </div> -->

<!-- end of navbar -->



    <%= yield %>
    <!-- footer -->
  </div>
    <div class="footer">
      <div class="footer-links">
        <a target="_blank" href="https://giphy.com/gifs/memecandy-LmNwrBhejkK9EFP504"><i class="fab fa-facebook"></i></a>
        <a target="_blank" href="https://giphy.com/gifs/memecandy-hrRJ41JB2zlgZiYcCw"><i class="fab fa-twitter"></i></a>
        <a target="_blank" href="https://giphy.com/gifs/cat-kitten-computer-3oKIPnAiaMCws8nOsE"><i class="fab fa-instagram"></i></a>
      </div>
      <div class="footer-copyright">
        <i class="fas fa-heart"></i>  Borja, César, Nick and Beatriz <i class="fas fa-heart"></i>
      </div>
    </div>
    <!-- end of footer -->
<!--     <script src="confetti.js"></script>
 -->  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/show.html.erb
<div id= "confetti" class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 We promise you will enjoy this experience</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>




<div class="d-flex justify-content-center">
  <div class="profile">
    <img class="avatar-large" alt="avatar-large" src="https://images.mubicdn.net/images/cast_member/2184/cache-2992-1547409411/image-w856.jpg?size=800x" />

    <p style= "font-size: 14px"><i class="fas fa-user-circle"></i> Tom Cruise</p>
    <p style= "font-size: 14px"><i class="fas fa-envelope"></i> 007@gmail.com</p>
    <p style= "font-size: 14px"><i class="fas fa-phone"></i> +34 007007</p>
    <p style= "font-size: 14px"><i class="fas fa-map-marker-alt"></i> London</p>
    <a class="btn btn-ghost" href="#">Edit profile</a>


  </div>


  <div class="box">
    <div class= "text">
      <div>
        <br>
        <h4 >Previous experiences :</h4>
        <br>
        <p><i class="fas fa-video"></i>  Harry Potter on the 6th of March 2019</p>
        <p><i class="fas fa-video"></i>  Shaun of the Dead on the 11th of June 2019</p>
        <!-- <td ><%#= current_user.booking_details %></td> -->
      </div>

      <div class= "nextexperience">
        <h4 >Your next experiences :</h4>
        <br>
        <p >Time of your booking :   <%= @user.bookings.last.booking_date.strftime('%d %B %Y') %></p>
        <p >You've picked :   <%= @user.bookings.last.experience.title %></p>
        <p >Your comment: <%= @user.bookings.last.booking_details %></p>
        <p >£<%= @user.bookings.last.experience.price %></p>
      </div>
    </div>

    <div class="button">
      <div class="d-flex justify-content-center" >
        <%= link_to  'Back to Experiences', experiences_path, class: "btn btn-ghost" %>
      </div>
    </div>
  </div>


</div>









<!-- CESAR CODE DOWN -->

<!-- <div class="student-profile py-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="card shadow-sm">
          <div class="card-header bg-transparent text-center">
            <img class="profile_img" src="https://kitt.lewagon.com/placeholder/users/cesar-bout" alt="">
            <h3>Name</h3>
          </div>
          <div class="card-body">
            <p class="mb-0"><strong class="pr-1">:</strong>4</p>
            <p class="mb-0"><strong class="pr-1">:</strong>A</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card shadow-sm">
          <div class="card-header bg-transparent border-0">
            <h3 class="mb-0"><i class="far fa-clone pr-1"></i>General Information</h3>
          </div>
 -->


<!--
          <div class="card-body pt-0">
            <table class="table table-bordered">
              <tr>
                <th width="30%">Previous experiences</th>
                <td width="2%">:</td>
                <td></td>
              </tr>
              <tr>
                <th width="30%">Experiences incoming </th>
                <td width="2%">:</td>
                <td></td>
              </tr>
              <tr>
                <th width="30%">Email</th>
                <td width="2%">:</td>
                <td></td>
              </tr>
              <tr>
                <th width="30%">Adress</th>
                <td width="2%">:</td>
                <td></td>
              </tr>
              <tr>
                <th width="30%">Telephone</th>
                <td width="2%">:</td>
                <td></td>
              </tr>
            </table>
          </div>
        </div>
          <div style="height: 26px"></div>
        <div class="card shadow-sm">
          <div class="card-header bg-transparent border-0">
            <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Other Information</h3>
          </div>
          <div class="card-body pt-0">
              <p>Why I am the best experiences' host</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> -->